### ISSUE TITLE
Please put in a version number

### ISSUE THREAD

**Issue by larkost-fetch** [datenhahn/imgcompare#1]
Programmaticly getting the version in the standard way (`imgcompare.__version__`) does not currently work. I can get it with `pkg_resources.get_distribution('imgcompare').version`, but that is a lot to remember.

The simple way to always keep thing in sync is to make a `version.py` file, and then write to that file as part of `setup.py`, then import it from `__init__.py` as `__version__`.

**Comment by datenhahn** [comment]
Thanks for the input, sorry for the (very) late feedback. Added a __version__ variable to `imgcompare/__init__.py` which is used in setup.py
